### ISSUE TITLE
Error after update to new version

### ISSUE THREAD

**Issue by mlava** [storvik/pythonremote#2]
Hello again,
Great work on updating to include sending notifications.
I had forked your repo with intention of trying to do so, but glad you did :)

Only problem, I am now getting an error when try to run:

Traceback (most recent call last):
  File "pythonremote.py", line 107, in <module>
    print_indata()
NameError: name 'print_indata' is not defined

Note that this only happens when trying to run the pythonremote.py script itself (as _python3 pythonremote.py_). If I call it using parameters it works fine.

Cheers.

**Comment by storvik** [comment]
Hi! 
This should be fixed now. 
Accidentally pressed M-t (transpose words) in emacs and swapped two words in my code. :laughing:

**Comment by mlava** [comment]
No worries. :+1:
