### ISSUE TITLE
NameError: name 'subprocess' is not defined.

### ISSUE THREAD

**Issue by frantonio** [storvik/pythonremote#3]
First of all, thanks for the awesome script. Secondly, while being in the process of configuring my computer i decided to delete the config files and start from scratch.
I input pythonremote --reset and i stumbled upon the following error:
" subprocess.call(['rm', config_path + 'autoremote.json'])
NameError: name 'subprocess' is not defined"
I avoided that message by writing "import subprocess" in the pythonremote.py file.
Perhaps that is of some help.

Greetings

**Comment by storvik** [comment]
Hello! 

Thank you for reporting this. 
Should be working again now.
